@echo off
echo Kompiliere AIDA64ToTcpIp.sln...
"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe" "../AIDA64ToTcpIp.sln" /Rebuild "Release"
echo Erstelle Setup für Client...
"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "AIDA64ToTcpIp_Client.iss"
echo Erstelle Setup für Server...
"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "AIDA64ToTcpIp_Server.iss"
pause